# D:\ansible-control-node\inventory.ini

[vps_lab]
vps_target ansible_host=host.docker.internal ansible_user=noah ansible_port=2222

[all:vars]       
ansible_become=yes           
ansible_become_password=ColdBrew
ansible_private_key_file=/ansible/Keys/vps_key 
host_key_checking=False 
ansible_ssh_common_args='-o StrictHostKeyChecking=no'