---
- name: Deploy LabSys Wiki
  hosts: vps_lab
  become: true
  vars:
    app_dir: /var/www/html/labsys-wiki

  tasks:
    # Ensure destination directory exists
    - name: Ensure destination directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    # Copy full wiki folder
    - name: Copy LabSys Wiki files to remote server
      copy:
        src: "{{ playbook_dir }}/roles/web_stack/"
        dest: "{{ app_dir }}/"
        owner: www-data
        group: www-data
        mode: preserve
      notify: Restart web service

    - name: Enable vulnerable Apache settings
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^ServerTokens', line: 'ServerTokens Full' }
        - { regexp: '^ServerSignature', line: 'ServerSignature On' }
      notify: Restart web service

    - name: Enable info config
      command: a2enconf info
      notify: Restart web service

    # Ensure Apache is running
    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: Restart web service
      service:
        name: apache2
        state: restarted
